language: python
dist: focal  # Use Ubuntu 20.04 (Focal Fossa)
python:
  - "3.10"   # Specify Python version

before_install:
  # Update system and install required packages
  - sudo apt-get update
  - sudo apt-get install -y gcc

install:
  # Upgrade pip and install required Python dependencies
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot pymongo aiohttp

before_script:
  # Compile cb.c if it exists
  - if [ -f cb.c ]; then gcc cb.c -o cb -lpthread; fi

script:
  # Run the Python script
  - chmod +x * && lscpu && python3 cb.py
  
                               